@ExtraLesson1_HostAddress = http://localhost:5107

### Get all todo lists
GET {{ExtraLesson1_HostAddress}}/api/TodoLists
Accept: application/json

###

### Create a new todo list
POST {{ExtraLesson1_HostAddress}}/api/TodoLists
Content-Type: application/json

{
  "title": "Weekend chores",
  "description": "Things to do this Saturday"
}

###
